theme:minima
title: My GitHub Website
author: Moin
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This just a demo page of my site on GitHub. This will be updated soon. Visit again, soon!!


show_excerpts: true # set to false to remove excerpts on the homepage
